---
abstract: 'Access Google Calendars using the v3 API'
author:
  - 'Rhesa Rozendaal <rhesa@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-CalendarV3
requires:
  DateTime::Format::ISO8601: 0
  JSON::XS: 0
  Kavorka: 0
  Moose: 0
  Try::Tiny: 0
  Types::Standard: 0
  WWW::JSON: 0
resources:
  repository: http://github.com/suitesetup/net-google-calendar
version: 0.07
